# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tam_rcpp_calc_exp <- function(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP) {
    .Call('_TAM_tam_rcpp_calc_exp', PACKAGE = 'TAM', NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP)
}

tam_rcpp_calc_exp_redefine_vector_na <- function(A, val) {
    .Call('_TAM_tam_rcpp_calc_exp_redefine_vector_na', PACKAGE = 'TAM', A, val)
}

tam_rcpp_calc_prob_subtract_max <- function(rr0M, NI, NK, TP) {
    .Call('_TAM_tam_rcpp_calc_prob_subtract_max', PACKAGE = 'TAM', rr0M, NI, NK, TP)
}

tam_rcpp_calc_prob_subtract_max_exp <- function(rr0, dim_rr) {
    .Call('_TAM_tam_rcpp_calc_prob_subtract_max_exp', PACKAGE = 'TAM', rr0, dim_rr)
}

tam_rcpp_calc_prob <- function(A, dimA, xsi, maxcat, AXsi0, iIndex, theta, B) {
    .Call('_TAM_tam_rcpp_calc_prob', PACKAGE = 'TAM', A, dimA, xsi, maxcat, AXsi0, iIndex, theta, B)
}

tam_rcpp_tam_mml_calc_prob_R_outer_Btheta <- function(Btheta, B_dd, theta_dd, dim_Btheta) {
    .Call('_TAM_tam_rcpp_tam_mml_calc_prob_R_outer_Btheta', PACKAGE = 'TAM', Btheta, B_dd, theta_dd, dim_Btheta)
}

tam_rcpp_tam_mml_calc_prob_R_normalize_rprobs <- function(rr, dim_rr) {
    .Call('_TAM_tam_rcpp_tam_mml_calc_prob_R_normalize_rprobs', PACKAGE = 'TAM', rr, dim_rr)
}

tam_rcpp_calc_suff_stat <- function(resp, resp_ind, maxK, nitems, pweights, cA) {
    .Call('_TAM_tam_rcpp_calc_suff_stat', PACKAGE = 'TAM', resp, resp_ind, maxK, nitems, pweights, cA)
}

tam_rcpp_ctt2 <- function(TDAT, WLE, MAXK, EST_WLE, prg) {
    .Call('_TAM_tam_rcpp_ctt2', PACKAGE = 'TAM', TDAT, WLE, MAXK, EST_WLE, prg)
}

tam_rcpp_ctt3 <- function(TDAT, WLE, MAXK, EST_WLE, prg) {
    .Call('_TAM_tam_rcpp_ctt3', PACKAGE = 'TAM', TDAT, WLE, MAXK, EST_WLE, prg)
}

tam_rcpp_fit_simul <- function(rn1M, c_hwt, Ax, xbar, var1, Uz2, Vz2, nstud_ip, pweights) {
    .Call('_TAM_tam_rcpp_fit_simul', PACKAGE = 'TAM', rn1M, c_hwt, Ax, xbar, var1, Uz2, Vz2, nstud_ip, pweights)
}

tam_rcpp_theta_sq <- function(theta) {
    .Call('_TAM_tam_rcpp_theta_sq', PACKAGE = 'TAM', theta)
}

tam_rcpp_interval_index <- function(MATR, RN) {
    .Call('_TAM_tam_rcpp_interval_index', PACKAGE = 'TAM', MATR, RN)
}

tam_rcpp_irt_likelihood_cfa <- function(data, nu, psi, L, theta) {
    .Call('_TAM_tam_rcpp_irt_likelihood_cfa', PACKAGE = 'TAM', data, nu, psi, L, theta)
}

tam_rcpp_mml_2pl_mstep_item_slopes_suffstat <- function(rprobs, items_temp, theta, dd, LIT, TP, nitems, maxcat, maxK, itemwt, xxf_, xbar_, xbar2_, irtmodel, xtemp_, items_conv) {
    .Call('_TAM_tam_rcpp_mml_2pl_mstep_item_slopes_suffstat', PACKAGE = 'TAM', rprobs, items_temp, theta, dd, LIT, TP, nitems, maxcat, maxK, itemwt, xxf_, xbar_, xbar2_, irtmodel, xtemp_, items_conv)
}

tam_rcpp_mml_3pl_calc_Fdes <- function(XDES, dimXdes) {
    .Call('_TAM_tam_rcpp_mml_3pl_calc_Fdes', PACKAGE = 'TAM', XDES, dimXdes)
}

tam_rcpp_mml_3pl_slca_deriv <- function(XdesM, dimXdes, Xlambda, probs, nik, Nik, guess, probs0) {
    .Call('_TAM_tam_rcpp_mml_3pl_slca_deriv', PACKAGE = 'TAM', XdesM, dimXdes, Xlambda, probs, nik, Nik, guess, probs0)
}

tam_rcpp_mml_3pl_calcexp <- function(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, rprobs0, GUESS, nik, ni) {
    .Call('_TAM_tam_rcpp_mml_3pl_calcexp', PACKAGE = 'TAM', NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, rprobs0, GUESS, nik, ni)
}

tam_rcpp_mml_3pl_compute_B <- function(Edes, gammaslope, dimE) {
    .Call('_TAM_tam_rcpp_mml_3pl_compute_B', PACKAGE = 'TAM', Edes, gammaslope, dimE)
}

tam_rcpp_mml_3pl_nonzero_entries <- function(E, dimE) {
    .Call('_TAM_tam_rcpp_mml_3pl_nonzero_entries', PACKAGE = 'TAM', E, dimE)
}

tam_rcpp_mml_mfr_gresp_extend <- function(gresp, xstep) {
    .Call('_TAM_tam_rcpp_mml_mfr_gresp_extend', PACKAGE = 'TAM', gresp, xstep)
}

tam_rcpp_mml_mfr_gresp_na_facets <- function(gresp, rnfacets, rnx) {
    .Call('_TAM_tam_rcpp_mml_mfr_gresp_na_facets', PACKAGE = 'TAM', gresp, rnfacets, rnx)
}

tam_rcpp_mml_mfr_a_matrix_cumsum <- function(index_matr, mm, SG) {
    .Call('_TAM_tam_rcpp_mml_mfr_a_matrix_cumsum', PACKAGE = 'TAM', index_matr, mm, SG)
}

tam_rcpp_mml_mfr_colsums_gresp <- function(gresp) {
    .Call('_TAM_tam_rcpp_mml_mfr_colsums_gresp', PACKAGE = 'TAM', gresp)
}

tam_rcpp_mml_maxcat <- function(A, dimA) {
    .Call('_TAM_tam_rcpp_mml_maxcat', PACKAGE = 'TAM', A, dimA)
}

tam_rcpp_modelfit_q3 <- function(residM, resp_bool) {
    .Call('_TAM_tam_rcpp_modelfit_q3', PACKAGE = 'TAM', residM, resp_bool)
}

tam_rcpp_modelfit_counts <- function(resp0, resp_bool, rprobs, hwt, maxKi, maxK) {
    .Call('_TAM_tam_rcpp_modelfit_counts', PACKAGE = 'TAM', resp0, resp_bool, rprobs, hwt, maxKi, maxK)
}

tam_rcpp_modelfit_ccov <- function(counts, scorematrix, adjust) {
    .Call('_TAM_tam_rcpp_modelfit_ccov', PACKAGE = 'TAM', counts, scorematrix, adjust)
}

tam_rcpp_modelfit_residuals <- function(rprobs, resp, I, TP, maxK, maxKi, hwt, resp_bool) {
    .Call('_TAM_tam_rcpp_modelfit_residuals', PACKAGE = 'TAM', rprobs, resp, I, TP, maxK, maxKi, hwt, resp_bool)
}

tam_rcpp_msq_itemfit <- function(resp, irf1, K, TP, post1, FIT, fitIndexM, resp_bool) {
    .Call('_TAM_tam_rcpp_msq_itemfit', PACKAGE = 'TAM', resp, irf1, K, TP, post1, FIT, fitIndexM, resp_bool)
}

tam_rcpp_prior_normal_density_unequal_means <- function(theta, mu, varInverse, COEFF) {
    .Call('_TAM_tam_rcpp_prior_normal_density_unequal_means', PACKAGE = 'TAM', theta, mu, varInverse, COEFF)
}

tam_rcpp_prior_normal_density_equal_means <- function(theta, mu, varInverse, COEFF) {
    .Call('_TAM_tam_rcpp_prior_normal_density_equal_means', PACKAGE = 'TAM', theta, mu, varInverse, COEFF)
}

tam_rcpp_pv_mcmc_likelihood <- function(probs, resp, resp_ind_bool, maxK, nstud, nitems) {
    .Call('_TAM_tam_rcpp_pv_mcmc_likelihood', PACKAGE = 'TAM', probs, resp, resp_ind_bool, maxK, nstud, nitems)
}

tam_rcpp_pv_mcmc_calc_probs_irf_3pl <- function(theta, B, I, maxK, resp_ind, AXsi) {
    .Call('_TAM_tam_rcpp_pv_mcmc_calc_probs_irf_3pl', PACKAGE = 'TAM', theta, B, I, maxK, resp_ind, AXsi)
}

tam_rcpp_pv_sample_theta_multidim <- function(post, theta) {
    .Call('_TAM_tam_rcpp_pv_sample_theta_multidim', PACKAGE = 'TAM', post, theta)
}

tam_rcpp_rowCumsums <- function(input) {
    .Call('_TAM_tam_rcpp_rowCumsums', PACKAGE = 'TAM', input)
}

tam_rcpp_tam_np_posterior <- function(dat2, dat_resp, probs0, pi_k, pweights, K1) {
    .Call('_TAM_tam_rcpp_tam_np_posterior', PACKAGE = 'TAM', dat2, dat_resp, probs0, pi_k, pweights, K1)
}

tam_rcpp_wle_suffstat <- function(RPROBS, CBL, CBB, CBBB, cndim, cnitems, cmaxK, cnstud, resp_ind) {
    .Call('_TAM_tam_rcpp_wle_suffstat', PACKAGE = 'TAM', RPROBS, CBL, CBB, CBBB, cndim, cnitems, cmaxK, cnstud, resp_ind)
}

tam_rcpp_wle_errinv <- function(myERR, cndim, cnstud) {
    .Call('_TAM_tam_rcpp_wle_errinv', PACKAGE = 'TAM', myERR, cndim, cnstud)
}

