## File Name: RcppExports.R
## File Version: 0.19
## File Last Change: 2017-08-17 17:36:17
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irt_likelihood_cfa2 <- function(data, nu, psi, L, theta) {
    .Call('TAM_irt_likelihood_cfa2', PACKAGE = 'TAM', data, nu, psi, L, theta)
}

msq_itemfit <- function(resp, irf1, K, TP, post1, FIT, fitIndexM) {
    .Call('TAM_msq_itemfit', PACKAGE = 'TAM', resp, irf1, K, TP, post1, FIT, fitIndexM)
}

msq_itemfit2 <- function(resp, irf1, K, TP, post1, FIT, fitIndexM) {
    .Call('TAM_msq_itemfit2', PACKAGE = 'TAM', resp, irf1, K, TP, post1, FIT, fitIndexM)
}

prior_normal_density_C <- function(theta, mu, varInverse, COEFF) {
    .Call('TAM_prior_normal_density_C', PACKAGE = 'TAM', theta, mu, varInverse, COEFF)
}

prior_normal_densityALL_C <- function(theta, mu, varInverse, COEFF) {
    .Call('TAM_prior_normal_densityALL_C', PACKAGE = 'TAM', theta, mu, varInverse, COEFF)
}

rowCumsums2_source <- function(input) {
    .Call('TAM_rowCumsums2_source', PACKAGE = 'TAM', input)
}

TAM_CALCEXP <- function(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT) {
    .Call('TAM_TAM_CALCEXP', PACKAGE = 'TAM', NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT)
}

TAM_CALCEXP2 <- function(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP) {
    .Call('TAM_TAM_CALCEXP2', PACKAGE = 'TAM', NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, NR, TP)
}

redefine_vector_na <- function(A, val) {
    .Call('TAM_redefine_vector_na', PACKAGE = 'TAM', A, val)
}

tam_ctt_C <- function(TDAT, WLE, MAXK, EST_WLE, prg) {
    .Call('TAM_tam_ctt_C', PACKAGE = 'TAM', TDAT, WLE, MAXK, EST_WLE, prg)
}

tamctt3csource <- function(TDAT, WLE, MAXK, EST_WLE, prg) {
    .Call('TAM_tamctt3csource', PACKAGE = 'TAM', TDAT, WLE, MAXK, EST_WLE, prg)
}

tam_fit_simul <- function(rn1M, c_hwt, Ax, xbar, var1, Uz2, Vz2, nstud_ip, pweights) {
    .Call('TAM_tam_fit_simul', PACKAGE = 'TAM', rn1M, c_hwt, Ax, xbar, var1, Uz2, Vz2, nstud_ip, pweights)
}

theta_sq_cpp <- function(theta) {
    .Call('TAM_theta_sq_cpp', PACKAGE = 'TAM', theta)
}

interval_index_C <- function(MATR, RN) {
    .Call('TAM_interval_index_C', PACKAGE = 'TAM', MATR, RN)
}

calc_prob_subtract_max <- function(rr0M, NI, NK, TP) {
    .Call('TAM_calc_prob_subtract_max', PACKAGE = 'TAM', rr0M, NI, NK, TP)
}

tam_mml_3pl_calc_Fdes <- function(XDES, dimXdes) {
    .Call('TAM_tam_mml_3pl_calc_Fdes', PACKAGE = 'TAM', XDES, dimXdes)
}

tam_mml_3pl_slca_deriv <- function(XdesM, dimXdes, Xlambda, probs, nik, Nik, guess, probs0) {
    .Call('TAM_tam_mml_3pl_slca_deriv', PACKAGE = 'TAM', XdesM, dimXdes, Xlambda, probs, nik, Nik, guess, probs0)
}

tam_mml_3pl_calcexp <- function(NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, rprobs0, GUESS, nik, ni) {
    .Call('TAM_tam_mml_3pl_calcexp', PACKAGE = 'TAM', NP, rprobs, A, INDEXIPNO, INDEXIPLIST2, ESTXSIINDEX, C, ITEMWT, rprobs0, GUESS, nik, ni)
}

tam_mml_3pl_compute_B_rcpp <- function(Edes, gammaslope, dimE) {
    .Call('TAM_tam_mml_3pl_compute_B_rcpp', PACKAGE = 'TAM', Edes, gammaslope, dimE)
}

tam_mml_3pl_nonzero_entries <- function(E, dimE) {
    .Call('TAM_tam_mml_3pl_nonzero_entries', PACKAGE = 'TAM', E, dimE)
}

gresp_extend <- function(gresp, xstep) {
    .Call('TAM_gresp_extend', PACKAGE = 'TAM', gresp, xstep)
}

gresp_na_facets <- function(gresp, rnfacets, rnx) {
    .Call('TAM_gresp_na_facets', PACKAGE = 'TAM', gresp, rnfacets, rnx)
}

a_matrix_cumsum <- function(index_matr, mm, SG) {
    .Call('TAM_a_matrix_cumsum', PACKAGE = 'TAM', index_matr, mm, SG)
}

colsums_gresp <- function(gresp) {
    .Call('TAM_colsums_gresp', PACKAGE = 'TAM', gresp)
}

tam_q3_calc_V2q3jack <- function(residM, resp_ind) {
    .Call('TAM_tam_q3_calc_V2q3jack', PACKAGE = 'TAM', residM, resp_ind)
}

tam_q3_calc_V2counts <- function(resp0, resp_ind, rprobs, hwt, maxKi, maxK) {
    .Call('TAM_tam_q3_calc_V2counts', PACKAGE = 'TAM', resp0, resp_ind, rprobs, hwt, maxKi, maxK)
}

tam_calccov <- function(counts, scorematrix, adjust) {
    .Call('TAM_tam_calccov', PACKAGE = 'TAM', counts, scorematrix, adjust)
}

tam_q3_calc_residM <- function(rprobs, resp, I, TP, maxK, maxKi, hwt) {
    .Call('TAM_tam_q3_calc_residM', PACKAGE = 'TAM', rprobs, resp, I, TP, maxK, maxKi, hwt)
}

tam_pv_mcmc_likelihood_Rcpp <- function(probs, resp, resp_ind, maxK, nstud, nitems) {
    .Call('TAM_tam_pv_mcmc_likelihood_Rcpp', PACKAGE = 'TAM', probs, resp, resp_ind, maxK, nstud, nitems)
}

tam_pv_mcmc_calc_probs_irf_3pl_rcpp <- function(theta, B, I, maxK, resp_ind, AXsi) {
    .Call('TAM_tam_pv_mcmc_calc_probs_irf_3pl_rcpp', PACKAGE = 'TAM', theta, B, I, maxK, resp_ind, AXsi)
}

tam_mvrnorm_rcpp <- function(n, mu, sigma) {
    .Call('TAM_tam_mvrnorm_rcpp', PACKAGE = 'TAM', n, mu, sigma)
}

tam_pv_weighted_mean <- function(theta, wgt) {
    .Call('TAM_tam_pv_weighted_mean', PACKAGE = 'TAM', theta, wgt)
}

tam_pv_weighted_cov <- function(theta, wgt) {
    .Call('TAM_tam_pv_weighted_cov', PACKAGE = 'TAM', theta, wgt)
}

tam_pv_sample_theta_multidim <- function(post, theta) {
    .Call('TAM_tam_pv_sample_theta_multidim', PACKAGE = 'TAM', post, theta)
}

tam_wle_Bs <- function(RPROBS, RESPIND, CBL, CBB, CBBB, cndim, cnitems, cmaxK, cnstud) {
    .Call('TAM_tam_wle_Bs', PACKAGE = 'TAM', RPROBS, RESPIND, CBL, CBB, CBBB, cndim, cnitems, cmaxK, cnstud)
}

tam_wle_errinv <- function(myERR, cndim, cnstud) {
    .Call('TAM_tam_wle_errinv', PACKAGE = 'TAM', myERR, cndim, cnstud)
}

